### ISSUE TITLE
I see we have some questionable QA on these pull requests

### ISSUE THREAD

**Issue by Talkarcabbage** [UIS-Capstone-Team2/C_Sharp_app#3]
What the heck is cccc98575f 
+ 246,604 additions

?????
For reference, the file is OverDue.txt and it contains approximately 240k lines of `123458542403`
What purpose does this serve exactly? Can I assume this is a severe implementation issue? Logger? Something?

**Comment by bcrumrin** [comment]
246,604 additions... thats the project. It went from empty and got pushed to full.
The overdue file contained about 200* lines of 12 digit numbers thats correct. The temp file wasnt cleared before the program used it. Wouldnt call it a severe implementation issue, one line of code fixed it. If youre wondering what it does, it keeps track of the overdue movies
